const gameData = [
  "Theif",
  "The Legend of Zelda",
  "Doom",
  "Call of Duty",
  "Assassin's Creed",
  "Minecraft",
  "Elder Scrolls",
  "Final Fantasy",
  "Battlefield",
  "Diablo",
  "Dark Souls",
  "Halo",
  "GTA",
  "Wolfenstein",
  "Overwatch",
  "GoldenEye 007",
  "Splinter Cell",
  "Metal Gear Solid",
  "Kings Quest",
  "The Secret of Monkey Island",
  "Ninja Gaiden",
  "Quake",
  "Resident Evil",
  "Mass Effect",
  "Quake 2",
  "Quake 3 Arena",
  "Fallout",
  "Cyberpunk 2077",
  "Elden Ring",
  "Horizon Zero Dawn",
  "Witcher 3: Wild Hunt",
  "Bloodborne",
  "Scorn",
  "Assassin's Creed Valhalla",
  "Need for Speed Heat",
  "Forza Horizon 4",
  "FIFA 21",
  "NBA 2K21",
  "Madden NFL 21",
  "Rocket League"
];
const genreData = [
  "Action",
  "Adventure",
  "Role-Playing",
  "Simulation",
  "Puzzle",
  "Idle",
  "Horror",
  "Strategy",
  "Sports",
];
const franchiseData = [
  "The Legend of Zelda",
  "Call of Duty",
  "Assassin's Creed",
  "Minecraft",
  "Elder Scrolls",
  "Final Fantasy",
  "Battlefield",
  "Diablo",
  "Dark Souls",
  "Halo",
  "GTA",
  "Wolfenstein",
  "Overwatch",
  "GoldenEye 007",
  "Splinter Cell",
  "Metal Gear Solid",
  "Kings Quest",
  "The Secret of Monkey Island",
  "Ninja Gaiden",
  "Quake",
  "Resident Evil",
  "Mass Effect",
  "Bloodborne",
  "Scorn"
];
